remote_theme: pages-themes/time-machine@v0.2.0

plugins:
  - jekyll-remote-theme

title: Facts
description: AI/ML Enthusiast | Backend Developer | GenAI Engineer

author: Facts

email: your_email@example.com

github_username: straightfacts07

show_downloads: false

markdown: kramdown

highlighter: rouge

timezone: Asia/Kolkata

permalink: pretty

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
