
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

title: factS
description: AI Engineer | Backend Developer | Machine Learning Enthusiast

author: factS

github_username: straightfacts07

show_downloads: false

markdown: kramdown
highlighter: rouge

timezone: Asia/Kolkata

permalink: pretty

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

# Optional SEO
lang: en

# GitHub Pages settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
